PRAGMA foreign_keys = ON;
CREATE TABLE users(id TEXT PRIMARY KEY, username TEXT NOT NULL COLLATE NOCASE UNIQUE, password_hash TEXT NOT NULL, recovery_hash TEXT NOT NULL, created_at INTEGER NOT NULL);
CREATE TABLE sessions(token_hash TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, csrf TEXT NOT NULL, expires_at INTEGER NOT NULL);
CREATE INDEX sessions_expiry ON sessions(expires_at);
CREATE TABLE hn_items(id INTEGER PRIMARY KEY, type TEXT NOT NULL, title TEXT, url TEXT, author TEXT, posted_at INTEGER NOT NULL, score INTEGER NOT NULL DEFAULT 0, descendants INTEGER NOT NULL DEFAULT 0, parent INTEGER, kids_json TEXT NOT NULL DEFAULT '[]', text_html TEXT NOT NULL DEFAULT '', deleted INTEGER NOT NULL DEFAULT 0, dead INTEGER NOT NULL DEFAULT 0, document_id TEXT, synced_at INTEGER NOT NULL);
CREATE INDEX hn_recent ON hn_items(type,posted_at DESC);
CREATE TABLE documents(id TEXT PRIMARY KEY,url TEXT NOT NULL,content_hash TEXT,r2_key TEXT,scope TEXT NOT NULL DEFAULT 'metadata',status TEXT NOT NULL DEFAULT 'pending',updated_at INTEGER NOT NULL);
CREATE TABLE analyses(content_hash TEXT NOT NULL,model TEXT NOT NULL,rubric TEXT NOT NULL,data_json TEXT NOT NULL,input_tokens INTEGER NOT NULL,created_at INTEGER NOT NULL,PRIMARY KEY(content_hash,model,rubric));
CREATE TABLE private_rules(id TEXT PRIMARY KEY,owner_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,name TEXT NOT NULL,prompt TEXT NOT NULL,compiled_json TEXT NOT NULL,draft_json TEXT,version INTEGER NOT NULL DEFAULT 1,state TEXT NOT NULL DEFAULT 'saved',created_at INTEGER NOT NULL,UNIQUE(id,owner_id));
CREATE INDEX rule_owner ON private_rules(owner_id);
CREATE TRIGGER limit_rules BEFORE INSERT ON private_rules WHEN (SELECT count(*) FROM private_rules WHERE owner_id=NEW.owner_id)>=3 BEGIN SELECT RAISE(ABORT,'rule_limit'); END;
CREATE TABLE evaluations(owner_id TEXT NOT NULL,rule_id TEXT NOT NULL,version INTEGER NOT NULL,content_hash TEXT NOT NULL,data_json TEXT NOT NULL,created_at INTEGER NOT NULL,PRIMARY KEY(owner_id,rule_id,version,content_hash),FOREIGN KEY(rule_id,owner_id) REFERENCES private_rules(id,owner_id) ON DELETE CASCADE);
CREATE TABLE user_item_state(owner_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,item_id INTEGER NOT NULL,hidden INTEGER NOT NULL DEFAULT 0,saved INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(owner_id,item_id));
CREATE TABLE checkpoints(key TEXT PRIMARY KEY,value TEXT NOT NULL,updated_at INTEGER NOT NULL);
CREATE TABLE jobs(id TEXT PRIMARY KEY,kind TEXT NOT NULL,payload TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN('pending','running','done','failed')),attempts INTEGER NOT NULL DEFAULT 0,not_before INTEGER NOT NULL,lease_until INTEGER NOT NULL DEFAULT 0,lease_token TEXT,dispatched_at INTEGER NOT NULL DEFAULT 0,error TEXT,created_at INTEGER NOT NULL);
CREATE INDEX jobs_due ON jobs(status,not_before,dispatched_at);
CREATE TABLE budgets(day TEXT NOT NULL,scope TEXT NOT NULL,amount INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(day,scope));
CREATE TABLE ai_calls(id TEXT PRIMARY KEY,job_id TEXT NOT NULL,day TEXT NOT NULL,reserved INTEGER NOT NULL,actual INTEGER,state TEXT NOT NULL CHECK(state IN('reserved','complete','uncertain')),created_at INTEGER NOT NULL);
CREATE TABLE feeds(id TEXT PRIMARY KEY,view_key TEXT NOT NULL,owner_id TEXT REFERENCES users(id) ON DELETE CASCADE,object_key TEXT NOT NULL,created_at INTEGER NOT NULL,expires_at INTEGER NOT NULL);
CREATE INDEX feeds_lookup ON feeds(view_key,created_at DESC);
CREATE INDEX feeds_expiry ON feeds(expires_at);
CREATE TABLE feed_heads(view_key TEXT PRIMARY KEY,feed_id TEXT NOT NULL REFERENCES feeds(id) ON DELETE CASCADE);
CREATE TABLE request_limits(key TEXT NOT NULL,bucket INTEGER NOT NULL,count INTEGER NOT NULL,PRIMARY KEY(key,bucket));
