import type { Item, Candidate, User, Feed, RuleRow } from './types.ts';
import { PRESETS } from './core.ts';
import { escapeHTML as e, richText, safeLink } from './security.ts';
export const csrfInput=(csrf:string)=>`<input type="hidden" name="csrf" value="${e(csrf)}">`;
export function layout(title:string,body:string,user:User|null=null,csrf='',notice=''){
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="strict-origin-when-cross-origin"><meta name="csrf-token" content="${e(csrf)}"><title>${e(title)} | JevNews</title><link rel="stylesheet" href="/style.css"><link rel="icon" href="/favicon.svg"><script defer src="/app.js"></script></head><body><table id="hnmain"><tbody><tr><td class="top"><div class="topbar"><a class="brand" href="/"><span class="logo">J</span> JevNews</a> <span class="nav"><a href="/newest">new</a> | <a href="https://news.ycombinator.com/front">past</a> | <a href="https://news.ycombinator.com/newcomments">comments</a> | <a href="/ask">ask</a> | <a href="/show">show</a> | <a href="/jobs">jobs</a> | <a href="https://news.ycombinator.com/submit" title="Submit on Hacker News">submit</a></span><span class="account">${user?`<a href="/account">${e(user.username)}</a> | <a href="/saved">saved</a> | <form class="inline" method="post" action="/logout">${csrfInput(csrf)}<button class="text-button">logout</button></form>`:'<a href="/login">login</a>'}</span></div></td></tr><tr><td>${notice?`<p class="notice">${e(notice)}</p>`:''}${body}</td></tr><tr><td class="footer"><a href="https://news.ycombinator.com/newsguidelines.html">Guidelines</a> | <a href="/about">About & privacy</a> | <a href="https://github.com/earayu/jevnews">Source</a> | <a href="https://news.ycombinator.com/">Hacker News</a><p>Independent reader. HN accounts and votes remain on Hacker News.</p><form action="https://hn.algolia.com/" method="get"><label>Search: <input name="q" size="20"></label></form></td></tr></tbody></table></body></html>`;
}
function age(time=0){const minutes=Math.max(0,Math.floor((Date.now()/1000-time)/60));return minutes<60?`${minutes} minutes ago`:minutes<1440?`${Math.floor(minutes/60)} hours ago`:`${Math.floor(minutes/1440)} days ago`;}
export function controls(selected:string,view:string,picks:boolean){
  return `<form class="controls" action="/" method="get"><label>view: <select name="view"><option value="jev" ${view==='jev'?'selected':''}>Jev</option><option value="hn" ${view==='hn'?'selected':''}>HN</option></select></label> <label>preset: <select name="preset">${Object.entries(PRESETS).map(([id,p])=>`<option value="${e(id)}" ${id===selected?'selected':''}>${e(p.name)}</option>`).join('')}</select></label> <label><input type="checkbox" name="picks" value="1" ${picks?'checked':''}>picks</label> <button>apply</button> | <a href="/rules">my rules</a> | <a href="/saved">saved</a> | <a href="/hidden">hidden</a></form>`;
}
export function itemRows(rows:Candidate[],start=0,user:User|null=null,csrf=''){
  return rows.map((c,index)=>{
    const i=c.item;if(i.dead||i.deleted)return '';
    const source=i.url?safeLink(i.url):`/item?id=${i.id}`;let host='';
    try{host=new URL(source).hostname.replace(/^www\./,'');}catch{}
    const label=c.analysis?`${c.analysis.kind}${c.analysis.scope==='metadata'?' · limited analysis':c.analysis.scope==='truncated'?' · partial text':''}`:'analysis pending';
    return `<tr class="athing" data-item="${i.id}"><td class="rank">${start+index+1}.</td><td class="vote"><a href="https://news.ycombinator.com/item?id=${i.id}" title="Vote on Hacker News" aria-label="Vote on Hacker News">▲</a></td><td class="title"><a href="${e(source)}">${e(i.title||'[untitled]')}</a>${host?` <span class="sitebit">(${e(host)})</span>`:''}</td></tr><tr data-item="${i.id}"><td colspan="2"></td><td class="subtext">${i.score||0} points by <a href="/user?id=${encodeURIComponent(i.by||'')}">${e(i.by||'[unknown]')}</a> <a href="/item?id=${i.id}">${age(i.time)}</a> | <a href="/item?id=${i.id}">${i.descendants?`${i.descendants} comments`:'discuss'}</a> | ${user?`<form class="inline" method="post" action="/item-state">${csrfInput(csrf)}<input type="hidden" name="id" value="${i.id}"><button class="text-button" name="action" value="hide">hide</button> | <button class="text-button" name="action" value="save">save</button></form>`:`<button class="text-button" data-local="hide" data-id="${i.id}">hide</button> | <button class="text-button" data-local="save" data-id="${i.id}">save locally</button>`} <span class="jev-tag">· ${e(label)}</span></td></tr><tr class="spacer" data-item="${i.id}"><td colspan="3"></td></tr>`;
  }).join('');
}
export function feedBody(rows:Candidate[],feed:Feed|null,url:URL,page:number,user:User|null,csrf:string){
  const more=new URL(url);if(feed)more.searchParams.set('snapshot',feed.id);more.searchParams.set('page',String(page+1));
  const ids=url.searchParams.get('picks')==='1'?feed?.picks:feed?.ids;
  return `${feed?`<div class="feed-meta" data-feed="${e(feed.view)}" data-version="${e(feed.id)}">${e(feed.coverage)} · ${e(new Date(feed.createdAt).toISOString())} <a hidden id="feed-update" href="${e(url.pathname+'?'+new URLSearchParams([...url.searchParams].filter(([k])=>!['snapshot','page'].includes(k))))}">new results available — refresh</a></div>`:''}<table class="itemlist"><tbody>${itemRows(rows,(page-1)*30,user,csrf)}${!rows.length?'<tr><td class="empty">No results yet. New items can be browsed in <a href="/newest">new</a>; analysis and private conditions may still be pending.</td></tr>':''}${ids&&page*30<ids.length?`<tr><td colspan="2"></td><td><a class="morelink" href="${e(more.pathname+more.search)}">More</a></td></tr>`:''}</tbody></table>`;
}
export function commentTree(root:Item,items:Map<number,Item>,depth=0,seen=new Set<number>()):string{
  if(depth>20||seen.has(root.id))return '';seen.add(root.id);
  return (root.kids||[]).map(id=>{
    const c=items.get(id);if(!c)return `<p class="comment-missing"><a href="/item?id=${id}">load reply</a></p>`;
    return `<details class="comment" open><summary><span class="comhead"><a href="/user?id=${encodeURIComponent(c.by||'')}">${e(c.by||'[deleted]')}</a> <a href="/item?id=${c.id}">${age(c.time)}</a> | <a href="https://news.ycombinator.com/item?id=${c.id}" title="Reply on Hacker News">reply on HN</a></span></summary><div class="comment-body">${c.deleted||c.dead?'[deleted]':richText(c.text||'')}<div class="children">${commentTree(c,items,depth+1,seen)}</div></div></details>`;
  }).join('');
}
export function itemBody(item:Item,comments:Map<number,Item>){
  return `<table class="itemlist"><tbody>${itemRows([{item,analysis:null}])}</tbody></table><div class="post-text">${item.deleted||item.dead?'[deleted]':richText(item.text||'')}</div><p class="post-text"><a href="https://news.ycombinator.com/item?id=${item.id}">Join the discussion on Hacker News</a></p><div class="comments">${commentTree(item,comments)}</div>`;
}
export function authForm(kind:'login'|'register'|'recover',csrf:string,siteKey:string){
  return `<div class="form-page"><h2>${kind==='recover'?'Recover account':kind}</h2><p>This is a JevNews account, not a Hacker News account.</p><form method="post" action="/${kind}">${csrfInput(csrf)}<label>username: <input name="username" required minlength="3" maxlength="24" autocomplete="username"></label>${kind==='recover'?'<label>recovery code: <input name="recovery" required autocomplete="off"></label>':''}<label>${kind==='recover'?'new ':''}password: <input type="password" name="password" required minlength="12" maxlength="128" autocomplete="${kind==='login'?'current-password':'new-password'}"></label>${siteKey?`<div class="cf-turnstile" data-sitekey="${e(siteKey)}" data-action="auth"></div><script src="https://challenges.cloudflare.com/turnstile/v0/api.js" defer></script>`:''}<button>${kind}</button></form><p><a href="/login">login</a> | <a href="/register">create account</a> | <a href="/recover">recover with code</a></p></div>`;
}
export function rulesBody(rows:RuleRow[],csrf:string){
  return `<div class="form-page"><h2>My reading rules</h2><p>Up to three private rules. Nothing is applied until you review and save it. Hard conditions do not silently accept unknown results.</p>${rows.map(r=>`<section><h3>${e(r.name)} <small>v${r.version} · ${e(r.state)}</small></h3><p>${e(r.prompt)}</p><form method="post" action="/rules/recompile">${csrfInput(csrf)}<input type="hidden" name="id" value="${e(r.id)}"><input type="hidden" name="version" value="${r.version}"><label>Revise your standards:<textarea name="prompt" maxlength="2000" rows="3" cols="80">${e(r.prompt)}</textarea></label><button>compile a new draft</button></form><form method="post" action="/rules/save">${csrfInput(csrf)}<input type="hidden" name="id" value="${e(r.id)}"><input type="hidden" name="version" value="${r.version}"><label>Executable rule (review/edit):<textarea name="compiled" rows="12" cols="80" required>${e(JSON.stringify(JSON.parse(r.draft_json||r.compiled_json),null,2))}</textarea></label><label><input type="checkbox" name="acknowledge" value="1">I understand any listed unsupported requirements are not executed.</label><button>save and apply</button></form><p><a href="/?rule=${e(r.id)}">read with saved rule</a></p><form method="post" action="/rules/delete">${csrfInput(csrf)}<input type="hidden" name="id" value="${e(r.id)}"><button>delete rule</button></form></section>`).join('')}<h3>Create a rule</h3><form method="post" action="/rules">${csrfInput(csrf)}<label>name: <input name="name" maxlength="60" required></label><label>starting preset: <select name="base">${Object.entries(PRESETS).map(([id,p])=>`<option value="${id}">${e(p.name)}</option>`).join('')}</select></label><label>Your reading standards:<textarea name="prompt" maxlength="2000" rows="5" cols="80" placeholder="More engineering experience; less promotion. Keep release announcements with implementation details."></textarea></label><button>create / compile for review</button></form><p>Natural-language compilation needs Workers AI. Until available, you can edit the structured rule yourself; your prose will not be silently treated as executed.</p></div>`;
}
